### ISSUE TITLE
fix: hooks-integration and custom-validation tests broken by tenant-scoped pooling

### ISSUE THREAD

**Issue by msywulak** [AtlasDevHQ/atlas#532]
## Problem

Two test files fail after #529 (tenant-scoped connection pooling) because their mocks don't include `isOrgPoolingEnabled`:

- `src/lib/plugins/__tests__/hooks-integration.test.ts` (6 failures)
- `src/lib/tools/__tests__/custom-validation.test.ts` (failures)

Error:
```
TypeError: connections.isOrgPoolingEnabled is not a function
```

at `packages/api/src/lib/tools/sql.ts:397`.

## Fix

Add `isOrgPoolingEnabled: () => false` to the `connections` mock in both test files (CLAUDE.md rule: mock all exports).

## Key files
- `packages/api/src/lib/plugins/__tests__/hooks-integration.test.ts`
- `packages/api/src/lib/tools/__tests__/custom-validation.test.ts`
