### ISSUE TITLE
fix(api,plugins): yaml-context AtlasMcpTool import + tsgo errors after #2190

### ISSUE THREAD

**Issue by msywulak** [AtlasDevHQ/atlas#2199]
Type-checking `packages/api` (tsgo --noEmit) on `main` (commit 43de507d) surfaces 5 errors stemming from `plugins/yaml-context/src/index.ts`:

```
src/lib/tools/__tests__/description-rubric.test.ts(174,34): error TS2339: Property 'mcpTools' does not exist on type 'AtlasContextPlugin<ContextYamlConfig>'.
../../plugins/yaml-context/src/index.ts(27,3): error TS2305: Module '"@useatlas/plugin-sdk"' has no exported member 'AtlasMcpTool'.
../../plugins/yaml-context/src/index.ts(286,21): error TS7031: Binding element 'filter' implicitly has an 'any' type.
../../plugins/yaml-context/src/index.ts(286,31): error TS7006: Parameter 'ctx' implicitly has an 'any' type.
../../plugins/yaml-context/src/index.ts(343,5): error TS2353: Object literal may only specify known properties, and 'mcpTools' does not exist in type 'AtlasContextPlugin<ContextYamlConfig>'.
```

Reproduces on a clean `main` checkout with `bun install && cd packages/api && bun x tsgo --noEmit` — likely a regression from #2190 (Plugin SDK MCP tools extension point) where `AtlasMcpTool` was renamed/moved from `@useatlas/plugin-sdk` and `mcpTools` was added to a different plugin variant than `AtlasContextPlugin`.

The reference impl in `plugins/yaml-context` declares `mcpTools` on `AtlasContextPlugin<ContextYamlConfig>` but the type doesn't carry that field — only `AtlasMcpTool`-shaped plugins do.

Fix likely: re-export `AtlasMcpTool` from the plugin-sdk barrel or move the `mcpTools` array to a separate plugin variant that the host can compose with `AtlasContextPlugin`.

Found while implementing #2073.
